//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
